import type { CompanyProfile, JobOffer, WorkerPublicProfile } from "./types";

export const demoCredentials = [
  { role: "Admin", name: "Administrador", email: "Admin", password: "1234", route: "/consola-admin" },
  { role: "Postulante", name: "Valentina Rojas", email: "valentina.rojas@demo.perfilprimero.cl", password: "Demo1234!", route: "/postulante" },
  { role: "Postulante", name: "Matias Araya", email: "matias.araya@demo.perfilprimero.cl", password: "Demo1234!", route: "/postulante" },
  { role: "Postulante", name: "Camila Fuentes", email: "camila.fuentes@demo.perfilprimero.cl", password: "Demo1234!", route: "/postulante" },
  { role: "Postulante", name: "Diego Morales", email: "diego.morales@demo.perfilprimero.cl", password: "Demo1234!", route: "/postulante" },
  { role: "Postulante", name: "Fernanda Silva", email: "fernanda.silva@demo.perfilprimero.cl", password: "Demo1234!", route: "/postulante" },
  { role: "Empresa", name: "Norte Digital SpA", email: "reclutamiento@nortedigital.demo", password: "Demo1234!", route: "/empresa" },
  { role: "Empresa", name: "Andes Operaciones SpA", email: "personas@andesoperaciones.demo", password: "Demo1234!", route: "/empresa" }
];

export const demoPostulants: WorkerPublicProfile[] = [
  {
    workerId: "demo-postulante-1",
    profileCode: "PP-VR01",
    displayName: "Especialista marketing performance",
    headline: "Especialista en marketing digital y performance",
    summary: "5 anos liderando campanas de Google Ads, Meta Ads y analitica GA4 para ecommerce y servicios.",
    skills: ["Google Ads", "Meta Ads", "GA4", "Looker Studio", "Ecommerce"],
    sectors: ["Marketing y Publicidad"],
    assessmentScores: { english: 82, spanish: 91, personality: 78 },
    cvAnalysisSummary: "Perfil orientado a performance, experimentacion y medicion comercial.",
    experienceLevel: "mid",
    yearsOfExperience: 5,
    region: "Region Metropolitana",
    city: "Providencia",
    workModes: ["remote", "hybrid"],
    expectedSalaryMin: 1200000,
    expectedSalaryMax: 1800000,
    currency: "CLP",
    availability: "listening",
    visibilityStatus: "visible",
    subscriptionStatus: "active",
    profileExpiresAt: new Date()
  },
  {
    workerId: "demo-postulante-2",
    profileCode: "PP-MA02",
    displayName: "Supervisor logistico",
    headline: "Supervisor de operaciones logisticas",
    summary: "7 anos coordinando turnos, rutas, inventario y KPI de centros de distribucion.",
    skills: ["WMS", "Excel", "Turnos", "Inventario", "KPI"],
    sectors: ["Abastecimiento y Logistica"],
    assessmentScores: { english: 54, spanish: 88, personality: 84 },
    cvAnalysisSummary: "Perfil solido para operaciones presenciales con liderazgo de equipos.",
    experienceLevel: "senior",
    yearsOfExperience: 7,
    region: "Region V",
    city: "Valparaiso",
    workModes: ["onsite"],
    expectedSalaryMin: 1000000,
    expectedSalaryMax: 1450000,
    currency: "CLP",
    availability: "actively_looking",
    visibilityStatus: "visible",
    subscriptionStatus: "active",
    profileExpiresAt: new Date()
  },
  {
    workerId: "demo-postulante-3",
    profileCode: "PP-CF03",
    displayName: "Analista contable",
    headline: "Analista contable y administrativo",
    summary: "Experiencia en facturacion, conciliacion, SII, ERP y reportes financieros mensuales.",
    skills: ["SII", "ERP", "Excel", "Conciliacion bancaria", "Facturacion"],
    sectors: ["Administracion, Contabilidad y Finanzas"],
    assessmentScores: { english: 48, spanish: 93, personality: 80 },
    cvAnalysisSummary: "Perfil administrativo-contable con foco en orden, cumplimiento y reportabilidad.",
    experienceLevel: "mid",
    yearsOfExperience: 4,
    region: "Region Metropolitana",
    city: "Santiago",
    workModes: ["hybrid", "onsite"],
    expectedSalaryMin: 850000,
    expectedSalaryMax: 1150000,
    currency: "CLP",
    availability: "listening",
    visibilityStatus: "visible",
    subscriptionStatus: "active",
    profileExpiresAt: new Date()
  },
  {
    workerId: "demo-postulante-4",
    profileCode: "PP-DM04",
    displayName: "Desarrollador frontend",
    headline: "Desarrollador frontend React",
    summary: "Construccion de interfaces React, Next.js, consumo de APIs y mejora de experiencia de usuario.",
    skills: ["React", "Next.js", "TypeScript", "Firebase", "CSS"],
    sectors: ["Tecnologia, Sistemas y Telecomunicaciones"],
    assessmentScores: { english: 76, spanish: 89, personality: 75 },
    cvAnalysisSummary: "Perfil tecnico frontend con buen calce para productos digitales y SaaS.",
    experienceLevel: "mid",
    yearsOfExperience: 3,
    region: "Region VIII",
    city: "Concepcion",
    workModes: ["remote", "hybrid"],
    expectedSalaryMin: 1500000,
    expectedSalaryMax: 2200000,
    currency: "CLP",
    availability: "actively_looking",
    visibilityStatus: "visible",
    subscriptionStatus: "active",
    profileExpiresAt: new Date()
  },
  {
    workerId: "demo-postulante-5",
    profileCode: "PP-FS05",
    displayName: "Ejecutiva atencion clientes",
    headline: "Ejecutiva de atencion al cliente y postventa",
    summary: "Manejo de CRM, reclamos, fidelizacion y seguimiento de casos para servicios masivos.",
    skills: ["CRM", "Postventa", "Atencion cliente", "Zendesk", "Ventas consultivas"],
    sectors: ["Atencion al Cliente, Call Center y Telemarketing"],
    assessmentScores: { english: 61, spanish: 95, personality: 87 },
    cvAnalysisSummary: "Perfil fuerte en comunicacion, seguimiento y experiencia de clientes.",
    experienceLevel: "mid",
    yearsOfExperience: 6,
    region: "Region X",
    city: "Puerto Montt",
    workModes: ["hybrid", "onsite"],
    expectedSalaryMin: 750000,
    expectedSalaryMax: 980000,
    currency: "CLP",
    availability: "listening",
    visibilityStatus: "visible",
    subscriptionStatus: "active",
    profileExpiresAt: new Date()
  }
];

export const demoCompanies: CompanyProfile[] = [
  {
    companyId: "demo-empresa-norte-digital",
    companyName: "Norte Digital SpA",
    legalName: "Norte Digital SpA",
    taxId: "76.345.210-8",
    website: "https://nortedigital.demo",
    industry: "Marketing y Publicidad",
    size: "11-50",
    verificationStatus: "verified",
    billingStatus: "active",
    reputationScore: 96,
    responseRate: 88,
    averageResponseTimeHours: 18
  },
  {
    companyId: "demo-empresa-andes-operaciones",
    companyName: "Andes Operaciones SpA",
    legalName: "Andes Operaciones SpA",
    taxId: "77.812.904-1",
    website: "https://andesoperaciones.demo",
    industry: "Abastecimiento y Logistica",
    size: "51-200",
    verificationStatus: "verified",
    billingStatus: "active",
    reputationScore: 92,
    responseRate: 81,
    averageResponseTimeHours: 24
  }
];

export const demoJobOffers: JobOffer[] = [
  offer("demo-oferta-1", demoCompanies[0].companyId, "Especialista SEO", "Marketing y Publicidad", "Region Metropolitana", "Providencia", 1, 1000000, 1500000),
  offer("demo-oferta-2", demoCompanies[0].companyId, "Analista paid media", "Marketing y Publicidad", "Region Metropolitana", "Las Condes", 2, 1200000, 1900000),
  offer("demo-oferta-3", demoCompanies[0].companyId, "Disenador UX/UI", "Diseno", "Region Metropolitana", "Santiago", 1, 1300000, 1800000),
  offer("demo-oferta-4", demoCompanies[0].companyId, "Desarrollador frontend", "Tecnologia, Sistemas y Telecomunicaciones", "Region VIII", "Concepcion", 1, 1600000, 2300000),
  offer("demo-oferta-5", demoCompanies[0].companyId, "Ejecutivo comercial B2B", "Comercial, Ventas y Negocios", "Region V", "Vina del Mar", 3, 850000, 1300000),
  offer("demo-oferta-6", demoCompanies[1].companyId, "Supervisor logistico", "Abastecimiento y Logistica", "Region V", "Valparaiso", 2, 1000000, 1450000),
  offer("demo-oferta-7", demoCompanies[1].companyId, "Analista inventario", "Produccion y Manufactura", "Region Metropolitana", "Pudahuel", 1, 850000, 1200000),
  offer("demo-oferta-8", demoCompanies[1].companyId, "Coordinador transporte", "Abastecimiento y Logistica", "Region X", "Puerto Montt", 1, 950000, 1350000),
  offer("demo-oferta-9", demoCompanies[1].companyId, "Analista contable operaciones", "Administracion, Contabilidad y Finanzas", "Region Metropolitana", "Santiago", 1, 900000, 1250000),
  offer("demo-oferta-10", demoCompanies[1].companyId, "Encargado atencion clientes", "Atencion al Cliente, Call Center y Telemarketing", "Region X", "Puerto Montt", 2, 700000, 950000)
];

function offer(
  jobOfferId: string,
  companyId: string,
  title: string,
  area: string,
  region: string,
  city: string,
  vacancies: number,
  salaryMin: number,
  salaryMax: number
): JobOffer {
  return {
    jobOfferId,
    companyId,
    title,
    area,
    region,
    city,
    workMode: "hybrid",
    contractType: "full_time",
    salaryMin,
    salaryMax,
    currency: "CLP",
    vacanciesTotal: vacancies,
    vacanciesAvailable: vacancies,
    description: `Proceso demo para ${title}. Incluye entrevista web, trazabilidad y cierre con pago de prueba.`,
    requirements: "Experiencia comprobable, comunicacion clara, disponibilidad y referencias laborales.",
    visibilityStatus: "visible"
  };
}
